In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame

In [2]:
flow = pd.read_csv('data/flow.csv')
speed = pd.read_csv('data/speed.csv')
flow.shape

(75166, 151)

In [3]:
flow['Timestamp'] = pd.to_datetime(flow['Timestamp'])
flow.set_index('Timestamp', inplace=True)
speed['Timestamp'] = pd.to_datetime(speed['Timestamp'])
speed.set_index('Timestamp', inplace=True)

flow = flow.sort_index()
speed = speed.sort_index()

flow

,715933,715938,715944,715947,716010,716081,716087,716143,716485,716626,...,772918,772932,773154,773179,773193,774672,774728,775155,775610,775734
Timestamp,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,306.0,372.0,345.0,420.0,300.0,270.0,309.6,204.0,214.0,199.2,...,285.0,324.0,194.4,342.0,318.0,436.0,750.0,512.0,472.0,402.0
2018-01-01 00:05:00,321.0,336.0,336.0,376.0,258.0,297.0,324.0,207.0,226.0,144.0,...,222.0,366.0,153.6,366.0,186.0,488.0,711.0,382.0,432.0,348.0
2018-01-01 00:10:00,375.0,363.0,312.0,316.0,300.0,336.0,355.2,177.0,192.0,252.0,...,336.0,348.0,235.2,381.0,336.0,548.0,765.0,534.0,524.0,420.0
2018-01-01 00:15:00,363.0,426.0,429.0,496.0,381.0,507.0,448.8,201.0,266.0,266.4,...,375.0,411.0,403.2,444.0,450.0,596.0,813.0,754.0,700.0,534.0
2018-01-01 00:20:00,399.0,474.0,390.0,672.0,516.0,546.0,537.6,273.0,282.0,261.6,...,411.0,612.0,441.6,486.0,522.0,724.0,831.0,866.0,872.0,612.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 23:35:00,582.0,642.0,516.0,824.0,282.0,516.0,580.8,270.0,328.0,360.0,...,450.0,576.0,364.8,504.0,534.0,872.0,354.0,672.0,1036.0,477.0
2018-12-31 23:40:00,531.0,606.0,531.0,768.0,240.0,537.0,535.2,261.0,252.0,328.8,...,375.0,519.0,321.6,417.0,429.0,712.0,390.0,666.0,952.0,450.0
2018-12-31 23:45:00,528.0,564.0,471.0,716.0,246.0,417.0,573.6,264.0,294.0,288.0,...,303.0,447.0,304.8,339.0,387.0,876.0,351.0,540.0,748.0,348.0
2018-12-31 23:50:00,333.0,474.0,465.0,508.0,183.0,483.0,271.2,267.0,246.0,247.2,...,357.0,438.0,276.0,282.0,309.0,792.0,240.0,514.0,700.0,288.0
2018-12-31 23:55:00,213.0,393.0,312.0,452.0,240.0,456.0,417.6,234.0,232.0,249.6,...,384.0,519.0,232.8,198.0,552.0,692.0,315.0,574.0,560.0,279.0

In [4]:
np.random.seed(5)

# Count total days
total_days = (flow.index.max() - flow.index.min()).days + 1

# 30 days of data are randomly selected as the test set
test_days = np.random.choice(total_days, 30, replace=False)

# test set
test_flow = flow.loc[flow.index.map(lambda x: (x - flow.index.min()).days + 1).isin(test_days)]
test_speed = speed.loc[speed.index.map(lambda x: (x - speed.index.min()).days + 1).isin(test_days)]

In [5]:
training_flow = flow.loc[~flow.index.map(lambda x: (x - flow.index.min()).days + 1).isin(test_days)]
training_speed = speed.loc[~speed.index.map(lambda x: (x - speed.index.min()).days + 1).isin(test_days)]

In [6]:
training_flow.to_csv('data/training_flow.csv')
training_speed.to_csv('data/training_speed.csv')

test_flow.to_csv('data/test_flow.csv')
test_speed.to_csv('data/test_speed.csv')